# Configurações básicas do Firebase
FIREBASE_API_KEY = "AIzaSyCItM3AhNWL2Piollx79bRShij8uDLg7Ec"
FIREBASE_AUTH_DOMAIN = "green-belt-six-sigma.firebaseapp.com"
FIREBASE_PROJECT_ID = "green-belt-six-sigma"
FIREBASE_STORAGE_BUCKET = "green-belt-six-sigma.firebasestorage.app"
FIREBASE_MESSAGING_SENDER_ID = "212288097474"
FIREBASE_APP_ID = "1:212288097474:web:91954932156199d20eff5b"

